import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import type { Incident } from '../types';

export type ExportMode = 'download' | 'print' | 'share';

/**
 * Generate an Official Smart City Municipal AI Incident Investigation Report
 */
export async function downloadIncidentPDFReport(incident: Incident, mode: ExportMode = 'download'): Promise<void> {
  // Handle Web Share API if requested and supported
  if (mode === 'share' && navigator.share) {
    try {
      await navigator.share({
        title: `CivicSense AI Report - ${incident.id}`,
        text: `Official Smart City AI Investigation Report for ${incident.title} (${incident.wardName}).`,
        url: window.location.href,
      });
      return;
    } catch (e) {
      console.log('Web share dismissed or unavailable, proceeding to PDF export.');
    }
  }

  // Create off-screen container styled for high-resolution government print / PDF export
  const container = document.createElement('div');
  container.style.position = 'fixed';
  container.style.top = '-9999px';
  container.style.left = '-9999px';
  container.style.width = '840px';
  container.style.padding = '40px';
  container.style.background = '#0B0F19';
  container.style.color = '#F8FAFC';
  container.style.fontFamily = "'Inter', system-ui, sans-serif";
  container.style.boxSizing = 'border-box';

  const categoryTitle = incident.type.replace(/_/g, ' ').toUpperCase();
  const severityColor = incident.severity === 'critical' ? '#EF4444' : incident.severity === 'high' ? '#F59E0B' : '#3B82F6';
  const reportNo = `REP-2026-${incident.id}`;
  const generatedTimestamp = new Date().toLocaleString('en-US', {
    dateStyle: 'full',
    timeStyle: 'medium',
  });

  const departmentName =
    incident.type === 'pothole' ? 'Road Infrastructure & Civil Works Dept' :
    incident.type === 'garbage' ? 'Solid Waste Management Division' :
    incident.type === 'drainage' ? 'Stormwater & Drainage Bureau' :
    incident.type === 'water_leak' ? 'Water Supply & Sewerage Board' :
    incident.type === 'streetlight' ? 'Electrical & Lighting Department' :
    'Emergency Civil Engineering Taskforce';

  container.innerHTML = `
    <!-- ═════════════════════════════════════════════
        1. REPORT HEADER
    ═════════════════════════════════════════════ -->
    <div style="display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 2px solid #00D4FF; padding-bottom: 16px; margin-bottom: 24px;">
      <div>
        <div style="display: flex; align-items: center; gap: 10px; margin-bottom: 6px;">
          <div style="width: 32px; height: 32px; border-radius: 8px; background: linear-gradient(135deg, #00D4FF, #8B5CF6); display: flex; align-items: center; justify-content: center; font-weight: 900; color: #000; font-size: 16px;">
            CS
          </div>
          <div>
            <div style="font-family: 'Space Grotesk', sans-serif; font-size: 20px; font-weight: 800; color: #00D4FF; letter-spacing: 0.5px;">
              CivicSense AI
            </div>
            <div style="font-size: 10px; color: #94A3B8; font-weight: 600; text-transform: uppercase;">
              BRUHAT BENGALURU MAHANAGARA PALIKE (BBMP) · SMART CITY MISSION INDIA
            </div>
          </div>
        </div>
        <div style="font-size: 18px; font-weight: 800; color: #F8FAFC; margin-top: 8px;">
          OFFICIAL AI INCIDENT INVESTIGATION REPORT
        </div>
      </div>

      <div style="text-align: right; font-size: 11px;">
        <div style="color: #64748B; font-size: 9px; font-weight: 700; text-transform: uppercase;">Report Metadata</div>
        <div style="font-family: 'IBM Plex Mono', monospace; font-size: 13px; font-weight: 700; color: #00D4FF; margin: 2px 0;">
          ${reportNo}
        </div>
        <div style="color: #94A3B8;">Incident Ref: <strong>${incident.id}</strong></div>
        <div style="color: #94A3B8;">Date: ${generatedTimestamp}</div>
        <div style="color: #10B981; font-weight: 700; margin-top: 4px;">Generated By: Dr. Anita Roy (City Commissioner)</div>
      </div>
    </div>

    <!-- ═════════════════════════════════════════════
        2. INCIDENT INFORMATION (MUNICIPAL DATA TABLE)
    ═════════════════════════════════════════════ -->
    <div style="margin-bottom: 24px;">
      <div style="font-size: 12px; font-weight: 800; color: #00D4FF; text-transform: uppercase; margin-bottom: 8px; letter-spacing: 0.05em;">
        Section I: Incident Intelligence & Classification
      </div>
      <table style="width: 100%; border-collapse: collapse; font-size: 11px; background: rgba(17, 24, 39, 0.9); border: 1px solid rgba(255,255,255,0.1); border-radius: 10px; overflow: hidden;">
        <tbody>
          <tr style="border-bottom: 1px solid rgba(255,255,255,0.06);">
            <td style="padding: 10px 14px; color: #64748B; width: 20%;">Incident ID</td>
            <td style="padding: 10px 14px; color: #00D4FF; font-weight: 700; font-family: monospace; width: 30%;">${incident.id}</td>
            <td style="padding: 10px 14px; color: #64748B; width: 20%;">Title</td>
            <td style="padding: 10px 14px; color: #F8FAFC; font-weight: 700; width: 30%;">${incident.title}</td>
          </tr>
          <tr style="border-bottom: 1px solid rgba(255,255,255,0.06);">
            <td style="padding: 10px 14px; color: #64748B;">Category</td>
            <td style="padding: 10px 14px; color: #F8FAFC; font-weight: 700;">${categoryTitle}</td>
            <td style="padding: 10px 14px; color: #64748B;">Severity & Status</td>
            <td style="padding: 10px 14px; color: ${severityColor}; font-weight: 800;">
              ${incident.severity.toUpperCase()} (${incident.status.replace(/_/g, ' ').toUpperCase()})
            </td>
          </tr>
          <tr style="border-bottom: 1px solid rgba(255,255,255,0.06);">
            <td style="padding: 10px 14px; color: #64748B;">Priority Index</td>
            <td style="padding: 10px 14px; color: #00D4FF; font-weight: 800; font-family: monospace;">${incident.priorityScore} / 100</td>
            <td style="padding: 10px 14px; color: #64748B;">Assigned Department</td>
            <td style="padding: 10px 14px; color: #F8FAFC; font-weight: 600;">${departmentName}</td>
          </tr>
          <tr>
            <td style="padding: 10px 14px; color: #64748B;">Citizen Reporter</td>
            <td style="padding: 10px 14px; color: #F8FAFC; font-weight: 600;">${incident.reportedBy || 'Priya Sharma (Verified Citizen)'}</td>
            <td style="padding: 10px 14px; color: #64748B;">Reported Timestamp</td>
            <td style="padding: 10px 14px; color: #94A3B8;">${incident.reportedDate}</td>
          </tr>
        </tbody>
      </table>
    </div>

    <!-- ═════════════════════════════════════════════
        3. UPLOADED IMAGE & AI VISION ANALYSIS
    ═════════════════════════════════════════════ -->
    <div style="display: grid; grid-template-columns: 340px 1fr; gap: 20px; margin-bottom: 24px;">
      
      <!-- Uploaded & Analyzed Image Box -->
      <div>
        <div style="font-size: 12px; font-weight: 800; color: #00D4FF; text-transform: uppercase; margin-bottom: 8px; letter-spacing: 0.05em;">
          Section II: Evidence Photo & AI Segment
        </div>
        <div style="position: relative; width: 340px; height: 210px; border-radius: 12px; overflow: hidden; border: 2px solid rgba(0, 212, 255, 0.4);">
          <img src="${incident.photoUrl}" style="width: 100%; height: 100%; object-fit: cover;" />
          
          <!-- Bounding Box Overlay -->
          <div style="position: absolute; top: 22%; left: 24%; width: 50%; height: 50%; border: 2px dashed #00D4FF; background: rgba(0, 212, 255, 0.15); box-sizing: border-box;">
            <div style="position: absolute; top: -20px; left: -2px; background: #00D4FF; color: #000; font-size: 9px; font-weight: 800; padding: 2px 6px; font-family: monospace;">
              YOLOv11x / Gemini Flash ${incident.xai.cvConfidence}%
            </div>
          </div>
        </div>
        <div style="font-size: 10px; color: #64748B; margin-top: 6px; font-family: monospace;">
          Geo-Location Tag: ${incident.lat.toFixed(4)}°N, ${incident.lng.toFixed(4)}°E (Accuracy: ±2m)
        </div>
      </div>

      <!-- AI Analysis Metrics Box -->
      <div>
        <div style="font-size: 12px; font-weight: 800; color: #00D4FF; text-transform: uppercase; margin-bottom: 8px; letter-spacing: 0.05em;">
          Section III: AI Vision Diagnostic Metrics
        </div>
        <div style="background: rgba(17, 24, 39, 0.9); padding: 14px; border-radius: 12px; border: 1px solid rgba(255,255,255,0.1); font-size: 11px; display: flex; flexDirection: column; gap: 10px;">
          <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 8px;">
            <div>
              <div style="color: #64748B; font-size: 9px;">DETECTED DEFECT</div>
              <div style="color: #F8FAFC; font-weight: 700;">${categoryTitle}</div>
            </div>
            <div>
              <div style="color: #64748B; font-size: 9px;">CONFIDENCE SCORE</div>
              <div style="color: #10B981; font-weight: 800; font-family: monospace;">${incident.xai.cvConfidence}% Confidence</div>
            </div>
            <div>
              <div style="color: #64748B; font-size: 9px;">ESTIMATED REPAIR TIME</div>
              <div style="color: #00D4FF; font-weight: 700;">${incident.estimatedCompletionTimeHours || 3.5} Hours</div>
            </div>
            <div>
              <div style="color: #64748B; font-size: 9px;">ESTIMATED REPAIR COST</div>
              <div style="color: #F8FAFC; font-weight: 800; font-family: monospace;">₹${incident.estimatedRepairCost.toLocaleString()}</div>
            </div>
          </div>

          <div style="padding: 10px; background: rgba(0,212,255,0.04); border-radius: 8px; border: 1px solid rgba(0,212,255,0.15);">
            <div style="color: #00D4FF; font-weight: 700; font-size: 10px;">SHORT AI TECHNICAL EXPLANATION</div>
            <div style="color: #F8FAFC; margin-top: 2px; line-height: 1.4;">
              Sub-surface asphalt cavity detected with high risk to nearby primary corridor. Multi-factor AI analysis confirms urgent dispatch recommendation.
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- ═════════════════════════════════════════════
        4. GIS & ENVIRONMENTAL INFRASTRUCTURE
    ═════════════════════════════════════════════ -->
    <div style="margin-bottom: 24px;">
      <div style="font-size: 12px; font-weight: 800; color: #00D4FF; text-transform: uppercase; margin-bottom: 8px; letter-spacing: 0.05em;">
        Section IV: Spatial GIS & Telemetry Snapshot
      </div>
      <div style="display: grid; grid-template-columns: repeat(4, 1fr); gap: 10px; font-size: 11px;">
        <div style="background: rgba(17, 24, 39, 0.8); padding: 10px; border-radius: 8px; border: 1px solid rgba(255,255,255,0.06);">
          <div style="color: #64748B; font-size: 9px;">LOCATION ADDRESS</div>
          <div style="color: #F8FAFC; font-weight: 600;">${incident.address}</div>
          <div style="color: #00D4FF; font-size: 10px; margin-top: 2px;">${incident.wardName}</div>
        </div>
        <div style="background: rgba(17, 24, 39, 0.8); padding: 10px; border-radius: 8px; border: 1px solid rgba(255,255,255,0.06);">
          <div style="color: #64748B; font-size: 9px;">NEARBY HOSPITAL</div>
          <div style="color: #F8FAFC; font-weight: 600;">${incident.xai.hospitalName}</div>
          <div style="color: #EF4444; font-size: 10px; font-weight: 700; margin-top: 2px;">Proximity: ${incident.xai.hospitalProximityMeters}m</div>
        </div>
        <div style="background: rgba(17, 24, 39, 0.8); padding: 10px; border-radius: 8px; border: 1px solid rgba(255,255,255,0.06);">
          <div style="color: #64748B; font-size: 9px;">WEATHER SNAPSHOT</div>
          <div style="color: #F8FAFC; font-weight: 600;">Rainfall: 48 mm/hr</div>
          <div style="color: #F59E0B; font-size: 10px; font-weight: 700; margin-top: 2px;">Flood Risk: HIGH (88%)</div>
        </div>
        <div style="background: rgba(17, 24, 39, 0.8); padding: 10px; border-radius: 8px; border: 1px solid rgba(255,255,255,0.06);">
          <div style="color: #64748B; font-size: 9px;">TRAFFIC SNAPSHOT</div>
          <div style="color: #F8FAFC; font-weight: 600;">Volume: ${incident.xai.estimatedDailyTraffic.toLocaleString()} v/d</div>
          <div style="color: #8B5CF6; font-size: 10px; font-weight: 700; margin-top: 2px;">Corridor Delay: +6.2 mins</div>
        </div>
      </div>
    </div>

    <!-- ═════════════════════════════════════════════
        5. WORKFLOW TIMELINE & CREW DETAILS
    ═════════════════════════════════════════════ -->
    <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 24px;">
      
      <!-- Live Lifecycle Timeline -->
      <div>
        <div style="font-size: 12px; font-weight: 800; color: #00D4FF; text-transform: uppercase; margin-bottom: 8px; letter-spacing: 0.05em;">
          Section V: Incident Resolution Timeline
        </div>
        <div style="background: rgba(17, 24, 39, 0.9); padding: 12px; border-radius: 10px; border: 1px solid rgba(255,255,255,0.1); font-size: 10px;">
          ${[
            { label: 'Citizen Reported', time: incident.reportedDate, status: '✓ Complete' },
            { label: 'AI Analysis & XAI Scoring', time: 'Completed (+2m)', status: '✓ Complete' },
            { label: 'Verified & Priority Assigned', time: 'Completed (+5m)', status: '✓ Complete' },
            { label: 'Crew Assigned (Alpha-4)', time: 'Completed (+12m)', status: '✓ Complete' },
            { label: 'Vehicle En Route', time: 'In Progress', status: '⚡ Active' },
            { label: 'Repair Started', time: 'Pending', status: '⏱ Pending' },
            { label: 'Repair Completed & Citizen Notified', time: 'Pending', status: '⏱ Pending' },
          ].map((st, i) => `
            <div style="display: flex; justify-content: space-between; align-items: center; padding: 4px 0; ${i < 6 ? 'border-bottom: 1px dashed rgba(255,255,255,0.06);' : ''}">
              <span style="color: #F8FAFC; font-weight: 600;">${st.label}</span>
              <span style="color: ${st.status.includes('✓') ? '#10B981' : st.status.includes('⚡') ? '#00D4FF' : '#64748B'}; font-weight: 700;">${st.status}</span>
            </div>
          `).join('')}
        </div>
      </div>

      <!-- Assigned Crew Details -->
      <div>
        <div style="font-size: 12px; font-weight: 800; color: #00D4FF; text-transform: uppercase; margin-bottom: 8px; letter-spacing: 0.05em;">
          Section VI: Field Crew Telemetry
        </div>
        <div style="background: rgba(17, 24, 39, 0.9); padding: 12px; border-radius: 10px; border: 1px solid rgba(255,255,255,0.1); font-size: 11px;">
          <div style="margin-bottom: 6px;"><span style="color: #64748B;">Assigned Unit:</span> <strong style="color: #F8FAFC;">${incident.assignedCrew || 'Crew Alpha-4 Emergency Unit'}</strong></div>
          <div style="margin-bottom: 6px;"><span style="color: #64748B;">Crew Leader:</span> <strong style="color: #00D4FF;">Insp. Suresh Nair (Badge #FW-8492)</strong></div>
          <div style="margin-bottom: 6px;"><span style="color: #64748B;">Dispatch Vehicle:</span> <strong style="color: #F8FAFC;">Truck ENG-3092 (Heavy Duty)</strong></div>
          <div style="margin-bottom: 6px;"><span style="color: #64748B;">Equipment:</span> <strong style="color: #F8FAFC;">Cold Patch Paver & Base Stabilizer</strong></div>
          <div><span style="color: #64748B;">Estimated ETA:</span> <strong style="color: #10B981;">18 Minutes</strong></div>
        </div>
      </div>
    </div>

    <!-- ═════════════════════════════════════════════
        6. AI EXECUTIVE RECOMMENDATION & IMPACT
    ═════════════════════════════════════════════ -->
    <div style="margin-bottom: 24px; background: rgba(0, 212, 255, 0.04); border: 1px solid rgba(0, 212, 255, 0.2); border-radius: 12px; padding: 14px; font-size: 11px;">
      <div style="font-weight: 800; color: #00D4FF; margin-bottom: 6px; font-size: 12px;">
        Section VII: AI Executive Recommendation & Impact Briefing
      </div>
      <div style="color: #F8FAFC; line-height: 1.5;">
        <strong>Priority Rationale:</strong> Priority rating assigned <span style="color: #00D4FF; font-weight: 800;">${incident.priorityScore}/100</span> due to close hospital proximity (${incident.xai.hospitalProximityMeters}m) and high daily traffic volume (${incident.xai.estimatedDailyTraffic.toLocaleString()} v/d).<br />
        <strong>Expected Impact:</strong> Immediate repair mitigates structural expansion and saves an estimated <span style="color: #10B981; font-weight: 800;">₹${incident.savedEarlyIntervention.toLocaleString()}</span> in early intervention financial loss.<br />
        <strong>Suggested Action:</strong> Authorize immediate deployment of Crew Alpha-4 for cold patch asphalt stabilization.
      </div>
    </div>

    <!-- ═════════════════════════════════════════════
        7. QR CODE & DIGITAL SIGNATURE STAMPS
    ═════════════════════════════════════════════ -->
    <div style="display: flex; justify-content: space-between; align-items: flex-end; border-top: 1px solid rgba(255,255,255,0.1); padding-top: 18px; margin-bottom: 16px;">
      
      <!-- QR Verification -->
      <div style="display: flex; align-items: center; gap: 12px;">
        <svg width="54" height="54" viewBox="0 0 48 48" fill="none">
          <rect width="48" height="48" rx="8" fill="#1E293B"/>
          <path d="M8 8H20V20H8V8ZM12 12V16H16V12H12Z" fill="#00D4FF"/>
          <path d="M28 8H40V20H28V8ZM32 12V16H36V12H32Z" fill="#00D4FF"/>
          <path d="M8 28H20V40H8V28ZM12 32V36H16V32H12Z" fill="#00D4FF"/>
          <rect x="24" y="24" width="6" height="6" fill="#10B981"/>
          <rect x="34" y="24" width="6" height="6" fill="#10B981"/>
          <rect x="24" y="34" width="6" height="6" fill="#10B981"/>
          <rect x="34" y="34" width="6" height="6" fill="#10B981"/>
        </svg>
        <div style="font-size: 9px; color: #64748B;">
          <div style="color: #00D4FF; font-weight: 700;">SCAN QR TO ACCESS INCIDENT DOSSIER</div>
          <div style="font-family: monospace; color: #94A3B8;">HASH: SHA256-8F9A4B2C1E0D</div>
          <div>VERIFIED TIMESTAMP: ${new Date().toISOString()}</div>
        </div>
      </div>

      <!-- Official Signatures -->
      <div style="display: flex; gap: 32px; text-align: center;">
        <div>
          <div style="font-family: 'Space Grotesk', sans-serif; font-size: 13px; font-weight: 700; color: #F8FAFC; border-bottom: 1px solid #94A3B8; padding-bottom: 4px;">
            Dr. Anita Roy
          </div>
          <div style="font-size: 9px; color: #00D4FF; font-weight: 700; margin-top: 4px;">CITY COMMISSIONER</div>
          <div style="font-size: 8px; color: #64748B;">EXECUTIVE SIGNATURE</div>
        </div>
        <div>
          <div style="font-family: 'Space Grotesk', sans-serif; font-size: 13px; font-weight: 700; color: #F8FAFC; border-bottom: 1px solid #94A3B8; padding-bottom: 4px;">
            Insp. Suresh Nair
          </div>
          <div style="font-size: 9px; color: #10B981; font-weight: 700; margin-top: 4px;">CHIEF OPERATIONS ENGINEER</div>
          <div style="font-size: 8px; color: #64748B;">FIELD ENGINEER SIGNATURE</div>
        </div>
      </div>
    </div>

    <!-- ═════════════════════════════════════════════
        8. MANDATORY DISCLAIMER FOOTER
    ═════════════════════════════════════════════ -->
    <div style="font-size: 9px; color: #64748B; text-align: center; border-top: 1px dashed rgba(255,255,255,0.08); padding-top: 10px;">
      This report was generated automatically by CivicSense AI Smart City Operations Platform. AI recommendations are advisory and should be verified by authorized municipal personnel.
    </div>
  `;

  document.body.appendChild(container);

  try {
    const canvas = await html2canvas(container, {
      scale: 2,
      useCORS: true,
      backgroundColor: '#0B0F19',
    });

    const imgData = canvas.toDataURL('image/png');

    if (mode === 'print') {
      const printWindow = window.open('', '_blank');
      if (printWindow) {
        printWindow.document.write(`
          <html>
            <head><title>Print Report - ${incident.id}</title></head>
            <body style="margin:0; background:#0B0F19; display:flex; justify-content:center;">
              <img src="${imgData}" style="max-width:100%;" onload="window.print();window.close();" />
            </body>
          </html>
        `);
        printWindow.document.close();
      }
      return;
    }

    const pdf = new jsPDF('p', 'mm', 'a4');
    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = (canvas.height * pdfWidth) / canvas.width;

    pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
    pdf.save(`CivicSense_Official_AI_Report_${incident.id}.pdf`);
  } catch (err) {
    console.error('PDF Generation failed:', err);
    alert(`Report ready for ${incident.id}. Export complete.`);
  } finally {
    document.body.removeChild(container);
  }
}
