from fastapi import APIRouter

router = APIRouter(tags=["Core Data"])

WARDS = [
    {
        "id": "w-1",
        "name": "Ward 1 - Metro Health Corridor",
        "code": "W-01",
        "zone": "Central North",
        "population": 48500,
        "councillor": "Dr. Anita Roy",
        "roadQuality": 88,
        "drainageCondition": 76,
        "streetlightAvailability": 94,
        "garbageCleanliness": 82,
        "resolutionTimeHours": 14,
        "citizenSatScore": 89,
        "overallScore": 86,
        "openComplaints": 8,
        "closedComplaints": 142,
        "budgetUtilized": 1450000,
        "budgetTotal": 2000000,
        "lat": 12.9716,
        "lng": 77.5946,
    },
    {
        "id": "w-2",
        "name": "Ward 2 - Heritage Commercial Hub",
        "code": "W-02",
        "zone": "Central East",
        "population": 62000,
        "councillor": "Vikram Seth",
        "roadQuality": 64,
        "drainageCondition": 58,
        "streetlightAvailability": 85,
        "garbageCleanliness": 61,
        "resolutionTimeHours": 32,
        "citizenSatScore": 68,
        "overallScore": 67,
        "openComplaints": 24,
        "closedComplaints": 198,
        "budgetUtilized": 2100000,
        "budgetTotal": 2500000,
        "lat": 12.9789,
        "lng": 77.6045,
    },
    {
        "id": "w-3",
        "name": "Ward 3 - Tech Innovation Belt",
        "code": "W-03",
        "zone": "South East",
        "population": 89000,
        "councillor": "Priya Sharma",
        "roadQuality": 92,
        "drainageCondition": 90,
        "streetlightAvailability": 98,
        "garbageCleanliness": 91,
        "resolutionTimeHours": 9,
        "citizenSatScore": 94,
        "overallScore": 93,
        "openComplaints": 5,
        "closedComplaints": 310,
        "budgetUtilized": 2890000,
        "budgetTotal": 3200000,
        "lat": 12.9352,
        "lng": 77.6245,
    },
    {
        "id": "w-4",
        "name": "Ward 4 - Riverside Residential",
        "code": "W-04",
        "zone": "South West",
        "population": 54000,
        "councillor": "Rajesh Kumar",
        "roadQuality": 52,
        "drainageCondition": 41,
        "streetlightAvailability": 71,
        "garbageCleanliness": 55,
        "resolutionTimeHours": 46,
        "citizenSatScore": 58,
        "overallScore": 53,
        "openComplaints": 38,
        "closedComplaints": 112,
        "budgetUtilized": 1800000,
        "budgetTotal": 2200000,
        "lat": 12.9250,
        "lng": 77.5850,
    },
    {
        "id": "w-5",
        "name": "Ward 5 - Industrial Freight Zone",
        "code": "W-05",
        "zone": "West Outer",
        "population": 39000,
        "councillor": "Mahesh Patil",
        "roadQuality": 44,
        "drainageCondition": 50,
        "streetlightAvailability": 68,
        "garbageCleanliness": 49,
        "resolutionTimeHours": 54,
        "citizenSatScore": 52,
        "overallScore": 51,
        "openComplaints": 42,
        "closedComplaints": 89,
        "budgetUtilized": 1950000,
        "budgetTotal": 2100000,
        "lat": 12.9600,
        "lng": 77.5300,
    },
]

PREDICTIVE_RISKS = [
    {
        "id": "PRZ-101",
        "zoneName": "Victoria Hospital Arterial Road (Km 2.4 - 3.1)",
        "wardId": "w-1",
        "wardName": "Ward 1 - Metro Health Corridor",
        "riskType": "road_failure",
        "failureProbabilityScore": 92,
        "roadAgeYears": 7.2,
        "heavyVehicleVolumePerDay": 16400,
        "rainfallForecastMm": 68,
        "pastRepairsCount": 11,
        "recommendedAction": "Micro-surfacing & Mill-and-Overlay asphalt before monsoon peak",
        "estimatedInterventionCost": 18500,
        "potentialDamageCostIfIgnored": 94000,
        "lat": 12.9740,
        "lng": 77.5955,
    },
    {
        "id": "PRZ-102",
        "zoneName": "Riverside Low-Lying Drainage Basin",
        "wardId": "w-4",
        "wardName": "Ward 4 - Riverside Residential",
        "riskType": "drainage_overflow",
        "failureProbabilityScore": 87,
        "roadAgeYears": 5.5,
        "heavyVehicleVolumePerDay": 7200,
        "rainfallForecastMm": 85,
        "pastRepairsCount": 8,
        "recommendedAction": "Automated Culvert Cleansing & High-Capacity Sump Pump Installation",
        "estimatedInterventionCost": 22000,
        "potentialDamageCostIfIgnored": 120000,
        "lat": 12.9230,
        "lng": 77.5840,
    },
    {
        "id": "PRZ-103",
        "zoneName": "Freight Logistics Highway Sector 4",
        "wardId": "w-5",
        "wardName": "Ward 5 - Industrial Freight Zone",
        "riskType": "water_leakage",
        "failureProbabilityScore": 81,
        "roadAgeYears": 9.8,
        "heavyVehicleVolumePerDay": 28000,
        "rainfallForecastMm": 40,
        "pastRepairsCount": 14,
        "recommendedAction": "Acoustic Leak Detection & Main Joint Sealing",
        "estimatedInterventionCost": 14000,
        "potentialDamageCostIfIgnored": 65000,
        "lat": 12.9580,
        "lng": 77.5280,
    },
    {
        "id": "PRZ-104",
        "zoneName": "Heritage Market Wholesale Bin Node",
        "wardId": "w-2",
        "wardName": "Ward 2 - Heritage Commercial Hub",
        "riskType": "garbage_overflow",
        "failureProbabilityScore": 78,
        "roadAgeYears": 4.1,
        "heavyVehicleVolumePerDay": 19000,
        "rainfallForecastMm": 30,
        "pastRepairsCount": 5,
        "recommendedAction": "Deploy Dual Smart Compactor Bins with Fill Sensors",
        "estimatedInterventionCost": 7500,
        "potentialDamageCostIfIgnored": 24000,
        "lat": 12.9800,
        "lng": 77.6060,
    },
]

DEPARTMENTS = [
    {
        "id": "dept-1",
        "name": "Roads & Infrastructure Engineering",
        "code": "PWD-RD",
        "headOfficer": "Chief Eng. Somnath Mukherjee",
        "allocatedBudget": 5000000,
        "spentBudget": 3420000,
        "activeCrews": 18,
        "totalCrews": 22,
        "avgResolutionDays": 2.1,
        "satisfactionRating": 88,
        "openIncidents": 14,
        "resolvedThisMonth": 184,
    },
    {
        "id": "dept-2",
        "name": "Stormwater & Drainage Management",
        "code": "SWD-DR",
        "headOfficer": "Superintending Eng. Rekha Varma",
        "allocatedBudget": 3800000,
        "spentBudget": 2750000,
        "activeCrews": 12,
        "totalCrews": 15,
        "avgResolutionDays": 3.4,
        "satisfactionRating": 79,
        "openIncidents": 19,
        "resolvedThisMonth": 128,
    },
    {
        "id": "dept-3",
        "name": "Solid Waste & Sanitation Operations",
        "code": "SWM-SAN",
        "headOfficer": "Director Ramesh Gowda",
        "allocatedBudget": 4200000,
        "spentBudget": 3100000,
        "activeCrews": 34,
        "totalCrews": 38,
        "avgResolutionDays": 0.8,
        "satisfactionRating": 84,
        "openIncidents": 9,
        "resolvedThisMonth": 412,
    },
    {
        "id": "dept-4",
        "name": "Water Supply & Sewerage Board",
        "code": "BWSSB",
        "headOfficer": "General Mgr. Sunita Rao",
        "allocatedBudget": 3200000,
        "spentBudget": 2150000,
        "activeCrews": 10,
        "totalCrews": 14,
        "avgResolutionDays": 1.9,
        "satisfactionRating": 91,
        "openIncidents": 7,
        "resolvedThisMonth": 96,
    },
]

CITIZENS = [
    {
        "id": "c-1",
        "name": "Arjun Mehta",
        "avatar": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
        "points": 2450,
        "rank": 1,
        "reportsSubmitted": 38,
        "verifiedFixes": 34,
        "badges": [
            {"id": "b-1", "title": "Road Guardian", "icon": "🛡️", "description": "Reported 10+ critical pothole defects verified by engineering", "earnedDate": "2026-05-12"},
            {"id": "b-2", "title": "Top Contributor", "icon": "👑", "description": "Ranked #1 Citizen Inspector in Metro Region", "earnedDate": "2026-06-01"},
            {"id": "b-3", "title": "Clean City Champion", "icon": "🧹", "description": "5+ verified sanitation reports resolved under 12 hours", "earnedDate": "2026-07-15"},
        ],
    },
    {
        "id": "c-2",
        "name": "Neha Reddy",
        "avatar": "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80",
        "points": 1980,
        "rank": 2,
        "reportsSubmitted": 29,
        "verifiedFixes": 26,
        "badges": [
            {"id": "b-4", "title": "Water Watcher", "icon": "💧", "description": "Early detection of major pipeline leakage saving 50k L water", "earnedDate": "2026-04-18"},
            {"id": "b-5", "title": "Community Reporter", "icon": "🎖️", "description": "Submitted over 25 verified civic complaints", "earnedDate": "2026-06-20"},
        ],
    },
    {
        "id": "c-3",
        "name": "Kavita Nair",
        "avatar": "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80",
        "points": 1720,
        "rank": 3,
        "reportsSubmitted": 24,
        "verifiedFixes": 22,
        "badges": [
            {"id": "b-5", "title": "Community Reporter", "icon": "🎖️", "description": "Submitted over 20 verified civic complaints", "earnedDate": "2026-03-10"},
        ],
    },
]


@router.get("/wards")
def get_wards():
    return WARDS

@router.get("/departments")
def get_departments():
    return DEPARTMENTS

@router.get("/predictive-risks")
def get_predictive_risks():
    return PREDICTIVE_RISKS

@router.get("/citizens")
def get_citizens():
    return CITIZENS
